"""Add index_within_group to MeasuringInstrument

Revision ID: b0d08833131e
Revises: 8ba69486bb06
Create Date: 2025-03-22 19:37:15.283369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d08833131e'
down_revision: Union[str, None] = '8ba69486bb06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('groups', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('measuring_instruments', sa.Column('index_within_group', sa.Integer(), nullable=True))
    op.alter_column('measuring_instruments', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('measuring_instruments', 'vri_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('measuring_instruments', 'org_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('measuring_instruments', 'mit_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('measuring_instruments', 'mit_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('measuring_instruments', 'mit_notation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('measuring_instruments', 'mi_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('nodes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('nodes', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('nodes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('measuring_instruments', 'mi_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('measuring_instruments', 'mit_notation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('measuring_instruments', 'mit_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('measuring_instruments', 'mit_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('measuring_instruments', 'org_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('measuring_instruments', 'vri_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('measuring_instruments', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('measuring_instruments', 'index_within_group')
    op.alter_column('groups', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('groups', 'node_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
